export const surpriseMePrompts = [
  'an armchair in the shape of an avocado',
  'a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers',
  'teddy bears shopping for groceries in Japan, ukiyo-e',
  'an oil painting by Matisse of a humanoid robot playing chess',
  'panda mad scientist mixing sparkling chemicals, digital art',
  "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
  '3D render of a cute tropical fish in an aquarium on a dark blue background, digital art',
  'an astronaut lounging in a tropical resort in space, vaporwave',
  'an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background',
  'a stained glass window depicting a hamburger and french fries',
  'a pencil and watercolor drawing of a bright city in the future with flying cars',
  'a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art',
  'A dystopian cityscape with towering skyscrapers and dark, smoggy skies',
  'An alien planet with multiple moons and strange, otherworldly creatures',
  'A futuristic space station orbiting a distant planet',
  'A cyberpunk street scene with neon lights and holographic advertisements',
  'A fantastical castle floating in the clouds, surrounded by a storm',
  'A post - apocalyptic wasteland with scavengers and mutated creatures',
  'A time - traveling adventure to a medieval castle or a futuristic metropolis',
  'A mysterious portal leading to another dimension or alternate reality',
  'A robot uprising in a futuristic city, with drones and androids taking over',
  'A genetically - engineered creature, such as a hybrid animal or a superhuman cyborg, navigating a futuristic city',
  'a fortune-telling shiba inu reading your fate in a giant hamburger, digital art',
  '"a sea otter with a pearl earring" by Johannes Vermeer',
  'an oil pastel drawing of an annoyed cat in a spaceship',
  'a painting of a fox in the style of Starry Night',
  'a bowl of soup that looks like a monster, knitted out of wool',
  'A plush toy robot sitting against a yellow wall',
  'A synthwave style sunset above the reflecting water of the sea, digital art',
  'Two futuristic towers with a skybridge covered in lush foliage, digital art',
  'A 3D render of a rainbow colored hot air balloon flying above a reflective lake',
  'A comic book cover of a superhero wearing headphones',
  'A centered explosion of colorful powder on a black background',
  'A photo of a Samoyed dog with its tongue out hugging a white Siamese cat',
  'A photo of a white fur monster standing in a purple room',
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  'A Samurai riding a Horse on Mars, lomography.',
  'A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography',
  'A realistic photograph of a young woman with blue eyes and blonde hair',
  'A man standing in front of a stargate to another dimension',
  'Spongebob Squarepants in the Blair Witch Project',
  'A velociraptor working at a hotdog stand, lomography',
  'A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens',
  'A BBQ that is alive, in the style of a Pixar animated movie',
  'A futuristic cyborg dance club, neon lights',
  'The long-lost Star Wars 1990 Japanese Anime',
  'A hamburger in the shape of a Rubik’s cube, professional food photography',
  'A Synthwave Hedgehog, Blade Runner Cyberpunk',
  'An astronaut encountering an alien life form on a distant planet, photography',
  'A surreal landscape featuring floating islands and a giant moon in the sky',
  'A cityscape of the future, with towering skyscrapers and flying cars',
  'A whimsical forest with talking animals and hidden fairy doors',
  'A portrait of a person made entirely out of flowers and plants',
  'An underwater scene with a mermaid, schools of colorful fish, and a shipwreck',
  'A steampunk - style airship soaring over a Victorian - era city',
  'A post - apocalyptic wasteland with ruined buildings and mutated creatures',
  'A whimsical tea party with eccentric characters and fanciful desserts',
  'A fantasy creature, such as a dragon or unicorn, in a mystical forest',
  'A futuristic laboratory with high - tech equipment and glowing neon lights',
  'A Dinosaur exploring Cape Town, photography',
  'A Man falling in Love with his Computer, digital art',
  'A photograph of a cyborg exploring Tokyo at night, lomography',
  'Dracula walking down the street of New York City in the 1920s, black and white photography',
  'Synthwave aeroplane',
  'A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm',
  'A Space Shuttle flying above Cape Town, digital art',
  'A magical girl fighting against evil forces with her powers.',
  'A group of superheroes saving the city from villains and monsters from another dimension',
  'A young ninja training to become the next Hokage',
  'A high school romance with drama and comedy',
  'A team of adventurers exploring mysterious ruins and ancient artifacts',
  'A futuristic mecha battle between giant robots and alien invaders',
  'A group of cute animal characters going on adventures and solving problems',
  'A fantasy world with elves, dwarves, dragons, and wizards',
  'A comedy show with wacky and quirky characters',
  'A supernatural horror story with ghosts and demons',
  'A pirate crew sailing the seas in search of treasure',
  'A music - themed show with a band or idol group',
  'A sports anime featuring a team of athletes striving for victory',
  'A slice - of - life anime following the daily lives of characters',
  'A superhero team fighting crime and saving the world',
  'A comedy adventure with a talking animal as the main character',
  'A magical world of fairies, unicorns, and mythical creatures',
  'A sci - fi anime set in a distant future with advanced technology and space travel',
  'A group of friends going on an epic adventure to save the world',
  'A post - apocalyptic anime where the world is on the brink of destruction',
];